version: '3.8'

services:
  customer_service:
    build: ./customers
    ports:
      - "5001:5000"
    volumes:
      - type: bind
        source: /Users/ranam/Desktop/final_project/database.db
        target: /app/database.db

  inventory_service:
    build: ./inventory
    ports:
      - "5002:5000"
    volumes:
      - type: bind
        source: /Users/ranam/Desktop/final_project/database.db
        target: /app/database.db

  sales_service:
    build: ./sales
    ports:
      - "5003:5000"
    environment:
      - INVENTORY_SERVICE_URL=http://inventory_service:5000
      - CUSTOMER_SERVICE_URL=http://customer_service:5000

networks:
  default:
    driver: bridge
